[project]
name = "iran-wildfire-mcp-server"
version = "0.1.0"
description = "MCP server for Iran Wildfire Detection"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "earthengine-api>=1.7.1",
    "flake8-pyproject>=1.2.4",
    "google-genai>=1.52.0",
    "httpx>=0.28.1",
    "is-in-iran>=0.1.0",
    "mcp[cli]>=1.23.3",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]


[tool.flake8]
max-line-length = 100
